### ISSUE TITLE
About Fit2form

### ISSUE THREAD

**Issue by Bailey-24** [Haichuan9706/UAV-practice#1]
Hi, this issues have no relationship about this repo.
I met you at the issues of Fit2Form project.
https://github.com/columbia-ai-robotics/fit2form/issues

Do you successfully  run the   Fit2Form project?
I have some problem running the code of Fit2Form project.

If you have some idea about the issues of Fit2Form project , please help me out. Thanks in advanced.

**Comment by Jasonleeo-cpu** [comment]
I've tried this project for several months, but I can't run it successfully. Maybe some files are lost.
I have checked the original issue and found that the author has replied to you. You can try the solution given by the author.

**Comment by Bailey-24** [comment]
Okay. Thank you for your reply.
